"""Notification Center V1 enums."""

STATUS_SCHEDULED = "SCHEDULED"
STATUS_READY = "READY"
STATUS_SENT = "SENT"
STATUS_READ = "READ"
STATUS_CANCELLED = "CANCELLED"
STATUS_FAILED = "FAILED"
ACTIVE_STATUSES = (STATUS_SCHEDULED, STATUS_READY, STATUS_SENT, STATUS_READ)

PRIORITY_LOW = "LOW"
PRIORITY_NORMAL = "NORMAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_CRITICAL = "CRITICAL"

ROLE_STUDENT = "STUDENT_SIDE"
ROLE_ADMIN = "ADMIN_SIDE"

CATEGORY_TIMELINE = "timeline"
CATEGORY_EXPERT = "expert"
CATEGORY_ACCOUNT = "account"
CATEGORY_OPS = "ops"

PROVIDER_IN_APP = "IN_APP"
PROVIDER_WEB_PUSH = "WEB_PUSH"
PROVIDER_FCM = "FCM"
PROVIDER_APNS = "APNS"

DEFAULT_DEADLINE_LADDER = (30, 14, 7, 3, 1, 0)
DEFAULT_QUIET_START = "22:00"
DEFAULT_QUIET_END = "08:00"
DEFAULT_TIMEZONE = "Asia/Shanghai"
MAX_SEND_RETRIES = 3

CSCA_EVENT_TYPES = (
    "CSCA_REGISTRATION_DEADLINE",
    "CSCA_EXAM_DATE",
    "CSCA_RESULT_DATE",
    "CSCA_PREPARATION",
)

TITLE_EVENT_HINTS = (
    # CSCA-specific hints MUST come before generic 考试 / 报名
    (("CSCA报名", "CSCA 报名"), "CSCA_REGISTRATION_DEADLINE"),
    (("CSCA考试", "CSCA 考试"), "CSCA_EXAM_DATE"),
    (("CSCA成绩", "CSCA 成绩"), "CSCA_RESULT_DATE"),
    (("CSCA准备", "CSCA 准备", "CSCA备考"), "CSCA_PREPARATION"),
    (("报名", "申请截止", "网申", "报名开放", "申请"), "APPLICATION_DEADLINE"),
    (("材料", "交材料", "材料截止"), "MATERIAL_DEADLINE"),
    (("考试", "笔试", "机考"), "EXAM_DATE"),
    (("面试",), "INTERVIEW_DATE"),
    (("语言", "托福", "雅思", "TOEFL", "IELTS"), "LANGUAGE_TEST"),
    (("签证", "居留"), "VISA_REMINDER"),
)

NON_DISMISSABLE_EVENTS = frozenset({"ELIGIBILITY_RISK", "APPLICATION_DEADLINE", "STUDENT_RISK"})
COMPLETED_TIMELINE_STATUSES = frozenset({"COMPLETED", "NOT_APPLICABLE"})
